version: 2.1

orbs:
  poetry: frameio/poetry@0.15.0

workflows:
  main:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    executor: poetry/default
    steps:
      - checkout
      - poetry/build
      - poetry/shell:
          args: poetry run pytest tests
          requires:
            - poetry/build
