version: 2.1

orbs:
  python38: circleci/python@3.8

jobs:
  build:
    executor: python38
    steps:
      - checkout
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - run: poetry install && poetry build
      - run:
        command: |
          poetry run pytest tests
