version: 2.1

jobs:
  build:
    working_directory: ~/cli-project
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - run: poetry install && poetry build
      - run: poetry run pytest --maxfail=1 tests
