version: 2.1

jobs:
  build:
    # directory where steps are run
    working_directory: ~/cli-project
    docker: # run the steps with Docker
      - image: circleci/python:3.8
        # environment: # environment variables for primary container
        #   PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - run: poetry install && poetry build
      #poetry env info --path
      - run: poetry run pytest --maxfail=1 tests
